- name: Assert | Check booleans
  assert:
    fail_msg: Some boolean variables cannot be recognised
    that:
    - boot_on_zfs is boolean
    - hardened_kernel is boolean
    - ssh_enabled is boolean
    - ssh_password_auth is boolean
    - zsh_default_shell is boolean

- name: Assert | Check accounts
  assert:
    fail_msg: At least one account must be installed
    that: accounts | length > 0 

- name: Assert | Check each account
  loop: "{{ accounts }}"
  assert:
    success_msg: Account {{ item.username }} looks ok
    fail_msg: The given account is misconfigured
    that:
    - item.username | length > 0
    - item.ssh_keys is defined or item.password is defined
    - item.is_system_user is boolean

- name: Pre-Install | Install Python
  include_tasks: nixos_pre_install_python.yml

- name: Assert | Check install_device
  assert:
   fail_msg: Cannot find the install device
   that:
   - install_device is string

- name: Pre-Install | ZFS
  include_tasks: nixos_pre_install_zfs.yml

- name: Install | Install the system
  include_tasks: nixos_install.yml

- name: Post-Install | Reboot
  include_tasks: nixos_post_install.yml
  
