- name: Pre-Install | Wipe the partition table
  tags:
  - pre-install
  - zfs
  command: sgdisk --zap-all {{ install_device }}

- name: Pre-Install | Make the UEFI partition
  tags:
  - pre-install
  - zfs
  command: sgdisk -n3:1M:+512M -t3:EF00 {{ install_device }}

- name: Pre-Install | Create the ZFS partition
  tags:
  - pre-install
  - zfs
  command: sgdisk -n1:0:0 -t1:BF01 {{ install_device }}

- name: Pre-Install | Create the pool
  tags:
  - pre-install
  - zfs
  command: |
    zpool create -f \
      -O mountpoint=none \
      -O atime=off \
      -O compression=lz4 \
      -O xattr=sa \
      -O acltype=posixacl \
      -o ashift=12 \
      -R /mnt \
      rpool {{ install_device }}1

- name: Pre-Install | Create the datasets
  tags:
  - pre-install
  - zfs
  command: zfs create -o mountpoint={{ item.mp }} {{ item.path  }}
  with_items:
  - mp: none
    path: rpool/root
  - mp: legacy
    path: rpool/root/nixos
  - mp: legacy
    path: rpool/root/nixos/store
  - mp: legacy
    path: rpool/home

- name: Pre-Install | Mount the datasets
  tags:
  - pre-install
  - zfs
  command:
    cmd: '{{ item }}'
    warn: false
  with_items:
  - mount -t zfs rpool/root/nixos /mnt
  - mkdir -p /mnt/nix/store
  - mount -t zfs rpool/root/nixos/store /mnt/nix/store
  - mkdir /mnt/home
  - mkdir -p /mnt/etc/nixos
  - mount -t zfs rpool/home /mnt/home

- name: Pre-Install | Make UEFI as a vfat partition
  tags:
  - pre-install
  - zfs
  command:
    cmd: '{{ item }}'
    warn: false
  with_items:
  - mkfs.vfat {{ install_device }}3
  - mkdir /mnt/boot
  - mount {{ install_device }}3 /mnt/boot

